config/routes.rb
EmployeeApp::Application.routes.draw do

  resources :employees

  resources :teams

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :name, :supervisor_id, :employee_profile_attributes, :team_ids, :photo

  has_many :team_memberships
  has_many :teams, :through => :team_memberships
  has_many :supervised_teams, :class_name => "Employee", :foreign_key => "supervisor_id" #go over this again!
  #need to specify foreign key bc it will assume supervised_teams_id, but there is no such key in Employee table

  has_many :real_supervised_teams, :class_name => "Team", :through => :team_memberships, :source => :team #go over this again!
  #need to specify source, but itll look for an association named real_suprvised_teams in team_memberships model.
  #The association is named 'team' in team_memberships model

  has_one :employee_profile, :inverse_of => :employee

  belongs_to :supervisor, :class_name => "Employee"
  #it'll look for supervisor class, but class name is actually employee

  accepts_nested_attributes_for :employee_profile

  validates :employee_profile, :name, :presence => true

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "200x200>" }, 
      :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
      :url => "/system/:attachment/:id/:style/:filename",
      :default_url => ActionController::Base.helpers.asset_path('missing.png')
end

app/models/employee_profile.rb
class EmployeeProfile < ActiveRecord::Base
  belongs_to :employee, :inverse_of => :employee_profile
  attr_accessible :address, :ssn
  validates :employee, :address, :ssn, :presence => true
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name, :member_ids
  has_many :memberships, :class_name => "TeamMembership"

  has_many :members, :through => :memberships, :source => :employee
  # goes through one of it's own associations 'memberships', in that class, there is no member association - so
  # need to specify the source

  #TODO: add supervisor_id column to team table - forgot about below association
  #belongs_to :supervisor, :class_name => "Employee"
  validates :name, :presence=> true
end

app/models/team_membership.rb
class TeamMembership < ActiveRecord::Base
  belongs_to :employee
  belongs_to :team
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def index
    #@employees = Employee.all
    @employees = Employee.page(params[:page]).per_page(12)
  end

  def new
    @employee = Employee.new
    @employee.build_employee_profile
  end

  def create
    @employee = Employee.new(params[:employee])
    if @employee.save
      redirect_to employees_url
    else
      flash.now[:errors] = @employee.errors.full_messages
      render :new
    end
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    @employee.attributes = params[:employee]
    if @employee.save
      redirect_to employee_url(@employee)
    else
      flash.now[:errors] = @employee.errors.full_messages
      render :edit
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(params[:team])
    if @team.save
      redirect_to teams_url
    else
      flash.now[:errors] = @team.errors.full_messages
      render :new
    end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])
    @team.attributes = params[:team]
    if @team.save
      redirect_to team_url(@team)
    else
      flash.now[:errors] = @team.errors.full_messages
      render :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper

  # def employee_thumbnail(emp)
  #   html = '<a href="/employees/#{emp.id}" class="thumbnail"></a>'
  #     if emp.photo_file_name
  #       html += <%=image_tag emp.photo.url(:thumb)%>
  #     <% end %>
  #     <%=emp.name%>
  #   </a>
  #   html.html_safe
  # end
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/employees/_employee.html.erb
<ul class="thumbnails">
<% @employees.each do |emp| %>
  <%= render :partial => "employee_thumbnail", :locals => {:emp => emp} %>
<% end %>
</ul>

app/views/employees/_employee_thumbnail.html.erb
<li class="span4">
  <a href="/employees/<%=emp.id%>" class="thumbnail">
    <%=image_tag emp.photo.url(:thumb)%>
    <%=emp.name%>
  </a>
</li>

app/views/employees/_form.html.erb
<%= form_for @employee, :html => {:multipart => true} do |f| %>
  <%= f.label :name, "Name:" %>
  <%= f.text_field :name %>
  <br>
  <%= f.fields_for :employee_profile do |sf| %>
    <%= sf.label :ssn, "SSN:" %>
    <%= sf.text_field :ssn %>
    <br>
    <%= sf.label :address, "Address:" %>
    <%= sf.text_field :address %>
  <% end %>
  <br>
  <%= "Supervisor:" %>
  <br>
  <%= f.collection_select(:supervisor_id, Employee.all, :id, :name, :prompt => true) %> 
  <br>
  <%= "Teams:" %>
  <% Team.all.each do |team| %>
    <label class="checkbox"> <%= team.name %>
    <%= check_box_tag( "employee[team_ids][]", team.id, @employee.team_ids.include?(team.id), :id=> "team_id_#{team.id}")%>
    </label>
  <% end %>
  <%= f.label :photo, "Photo:" %>
  <%= f.file_field :photo %>
  <br>
  <%= hidden_field_tag "employee[team_ids][]", "" %>
  <br>
  <%= f.submit %>
<% end %>

app/views/employees/edit.html.erb
<h1><%= "Edit #{@employee.name}" %></h1>
<%= render :partial => "form" %>

app/views/employees/index.html.erb
<h1> Employees </h1>
<div id="employees">
<%= render :partial => "employee" %>

<%#= link_to "Create New Employee" ,new_employee_url , :class => "btn btn-large btn-primary" %>
<br>
</div>
<%= link_to "Create New Employee" ,new_employee_url , :class => "btn btn-large" %>
<%= will_paginate @employees %>

app/views/employees/new.html.erb
<h1> New Employee </h1>

<%= render :partial => "form" %>

app/views/employees/show.html.erb
<h1> <%= @employee.name %> </h1>
<div class="row-fluid">

  <div class="span2">
    <%= image_tag @employee.photo.url(:medium) %>
  </div>
    
  <div class="span5">
    <%= "SSN: #{@employee.employee_profile.ssn}" %>
    <br>
    <%= "Address: #{@employee.employee_profile.address}" %>
    <br>
    <%= "Supervisor:"%>
    <% if @employee.supervisor %>
      <%= link_to "#{@employee.supervisor.name}", employee_url(@employee.supervisor) %>
    <% end %>
    <br>
    <br>
    <strong><%= "Teams:" %></strong>
    <br>
    <% @employee.teams.each do |team| %>
      <%= link_to team.name, team_url(team) %>
    <% end %>

    <br>
    <br>
    <strong><%= "Direct Underlings:" %></strong>
    <br>
    <% @employee.supervised_teams.each do |team| %>
      <%= link_to team.name, employee_url(team) %>
      <br>
    <% end %>
    <br>
    <strong><%= "Supervised Teams:" %></strong>
    <br>
    <% @employee.real_supervised_teams.each do |team| %>
      <%= link_to team.name, team_url(team) %>
      <br>
    <% end %>

  </div>
</div>
<br>
<br>
<%= link_to "Edit Employee", edit_employee_url(@employee), :class => "btn btn-large btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmployeeApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<ul class="nav nav-tabs">
  <li><%= link_to "Employees", employees_url %></li>
  <li><%= link_to "Teams", teams_url %> </li>
</ul>
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
<% end %>
<div class="container-fluid">
  <%= yield %>
</div>
</body>
</html>